// <auto-generated />
namespace Khati.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class SSS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SSS));
        
        string IMigrationMetadata.Id
        {
            get { return "202509170413421_SSS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
